---
# tasks file for mate

- name: install software
  package:
    name: "{{ mate_packages }}"
    state: present
  when:
    - ansible_os_family != "RedHat"

- name: install software with excluded
  package:
    name: "{{ mate_packages }}"
    state: present
    exclude: "{{ mate_exclude | default(omit) }}"
  when:
    - ansible_os_family == "RedHat"

- name: ensure NetworkManager is started and enabled
  service:
    name: NetworkManager
    state: started
    enabled: yes
  when:
    ansible_os_family == "RedHat"
