---
# tasks file for mate
- name: install software
  package:
    name: "{{ mate_packages }}"
    state: present
  register: mate_install_software
  until: mate_install_software is succeeded
  retries: 3
  when:
    - ansible_os_family != "RedHat"

- name: install software with excluded
  package:
    name: "{{ mate_packages }}"
    state: present
    exclude: "{{ mate_exclude | default(omit) }}"
  register: mate_install_software_with_excluded
  until: mate_install_software_with_excluded is succeeded
  retries: 3
  when:
    - ansible_os_family == "RedHat"

- name: ensure NetworkManager is started and enabled
  service:
    name: NetworkManager
    state: started
    enabled: yes
  when:
    ansible_os_family == "RedHat"
